name = "MLNanoShaper"
uuid = "0ae43799-6878-4589-9bc9-cf11e8180012"
authors = ["tristan <tristan.hacquard@polytechnique.org> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
