[protein]
list = [
 "1ABO",
 "1ABO",
 "2O88",
 "1BBZ",
 "4J9I",
 "4J9C",
 "4J9I",
 "1BBZ",
 "4J9F",
 "4J9G",
 "3EG1",
 "4J9E",
 "4J9D",
 "4J9D",
 "1BBZ",
 "4J9E",
 "1BBZ",
 "4J9H",
 "4J9H",
 "4J9E",
 "4J9I",
 "4J9D",
 "1UTI",
 "2VWF",
 "4CC3",
 "4J9H",
 "4J9F",
 "4J9G",
 "4J9G",
 "4J9H",
 "4J9H",
 "3U23",
 "1UJ0",
 "4CC3",
 "4CC7",
 "4J9H",
 "3EG1",
 "4CC7",
 "4CC7",
 "2O88",
 "1OEB",
 "2P4R",
 "4CC3",
 "1AZE",
 "5OAV",
 "7A2W",
 "3GBQ",
 "2J7I",
 "2GBQ",
 "2DF6",
 "2J6O",
 "1FYN",
 "2J7I",
 "1B07",
 "2J6F",
 "4CC7",
 "5QU2",
 "4CC7",
 "4CC3",
 "6ATV",
 "7A2Y",
 "3THK",
 "4RTY",
 "2W0Z",
 "4RTW",
 "1W70",
 "4WCI",
 "5QU2",
 "3THK",
 "4GBQ",
 "5L23",
 "5XHZ",
 "7A2X",
 "4CC7"
]

